### ISSUE TITLE
Replace Python scripts with Vale programs

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#105]
The current Python scripts (build valec.py / testing valetest.py) function quite well, so this is more of a feature request with low priority.

Quoting Verdagon from a previous closed issue #81:
" I'm not really sure of a good short-term patch for the python version problem. Hopefully soon, we'll be able to completely replace our python scripts with Vale programs, which won't have these same problems. I'll leave this open until then. "

The Python version must be >= 3.8, and on Windows a 32 bit installer must be used, even on 64 bit systems. 

The possible advantages are:
 - removing the Python dependency
 - the Vale language must be advanced enough to handle this script-like functionality.

**Comment by Verdagon** [comment]
Done in #302!
