### ISSUE TITLE
Passing a tuple as parameter to a function and returning a tuple from a function

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#110]
I want to pass this tuple (or array?) 

m = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ];

to a function:

```
fn search(m Type, s int) infer-ret {  
  eachI sm (i, m1){   
    eachI m1 (j, val){
		  if (val == s) {
				ret [true, i, j];
			}
		}
	}
  ret [false, 0, 0];
}
```

This searches the indices (i, j) of a search-value s in m.

**Question 1:**  what is the type Type of m? 

Type: m  [3 * [3 * int]]               doesn't work.
Neither does:  m Array<mut, Array<mut, int>>,
Nor:     **m  [3][3] int**     <-- this is the preferred syntax when it gets implemented.

**Question 2:**  what is the return type of the function search? 
               
Interestingly, with the function signature:

fn search(m &Array<mut, Array<mut, int>>, s int) infer-ret { ... }

the compile error changes to:

pi20.vale:63:22 Can't infer return type because 2 types are returned:Set(
Coord(Share,TupleT2(List(Coord(Share,Bool2()), Coord(Share,Int2()), Coord(Share,Int2())),StructRef2(FullName2(List(),TupleName2(List(Coord(Share,Bool2()), Coord(Share,Int2()), Coord(Share,Int2()))))))),
Coord(Share,Void2()))

Same error when returning a tuple of 3 int's (like [1, i,  j] and [0 , 0, 0]

When changing the return type for this case to  Array<mut, int>, the error is:

pi20.vale:63:22 Can't infer return type because 2 types are returned:Set(
Coord(Share,KnownSizeArrayT2(3,RawArrayT2(Coord(Share,Int2()),Immutable))),
Coord(Share,Void2()))

So it seems the problem of the return type is that Vale thinks that there can also be a return case of type void,
whereas in this last case always a tuple of 3 ints is returned.

Attaching the complete code in zip format:
[pi20.zip](https://github.com/ValeLang/Vale/files/6136591/pi20.zip)

**Comment by Verdagon** [comment]
Fixed at head! With some changes to the code, to use the new arrays: https://gist.github.com/Verdagon/cc9970e0e3742b3e7d670af6a315d8f9

Won't quite mark it fixed yet, as I'd like to add the new array type syntax (like you said, `[3][3]int`). Stay tuned!

**Comment by Verdagon** [comment]
Actually, I'm gonna hold off a bit on the new type syntax, since there were recently some ideas on some better syntax. I'll close this, and open a more specific #204.

Anyway, passing a tuple is now possible, so marking this fixed. Will also verify on windows during the release. Thanks for reporting this Ivo!
