### ISSUE TITLE
Version info of Vale platform

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#113]
There should be an easy CLI command to see the current version of the Vale platform, something like:

c:\Vale\code_examples>python -V
Python 3.8.7

or:

c:\Vale\code_examples>rustc -V
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Comment by Verdagon** [comment]
Fixed as of #209, thanks for the idea Ivo!
