### ISSUE TITLE
Problem using float type on Windows 10

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#114]
(Using Vale 0.1.1)

Using the following test program float_operations.vale:

```
fn main() export {
  a = 42.9;
  b = 108.4;
}
```

Compiling this with python ..\valec.py build float_operations.vale gives the compilation error:
![image](https://user-images.githubusercontent.com/963452/111294276-6ed3ac80-864a-11eb-9594-830fe7c260b5.png)

When pushing any of the Abort - Retry - Ignore buttons the terminal shows:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast float_operations.vale
Running: C:\Vale\valec.EXE --verify --output-dir . build.vast
**valec couldn't compile build.vast:
Region override: assist
Warning: not using census when in assist mode!

Assertion failed: C->getType()->isFPOrFPVectorTy() && Ty->isFPOrFPVectorTy() && "Invalid cast", file C:\Users\Valerian\Downloads\llvm-project-llvmorg-11.0.1\llvm\lib\IR\Instructions.cpp, line 3069**

The same program running Ubuntu 20 under WSL in Windows compiles and runs without problems:
![image](https://user-images.githubusercontent.com/963452/111295568-d1797800-864b-11eb-8f57-a00ea031e746.png)

When running the test program round.vale from samples, I get the exact same error on Windows. However in Ubuntu 20 (WSL) I also get a compilation error:
![image](https://user-images.githubusercontent.com/963452/111300375-4dc28a00-8651-11eb-9b53-4458a92b4fb6.png)

- Same error occurs when:
```
  pi = 3.1415;
  println(pi.str());
```

**Comment by Verdagon** [comment]
Fixed as of #208, and verified on windows!
