### ISSUE TITLE
Problem in adding floats

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#115]
When adding the line:     c = a + b;
to the program in issue #114 

gives the same Microsoft Visual C++ Runtime dialog as shown in that issue, but another failed assertion:

c:\Vale\code_examples>python ..\valec.py build float_operations.vale
Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast float_operations.vale
Running: C:\Vale\valec.EXE --verify --output-dir . build.vast
valec couldn't compile build.vast:
Region override: assist
Warning: not using census when in assist mode!

**Assertion failed: false, file C:\Users\Valerian\Vale\Midas\src\c-compiler\function\expressions\externs.cpp, line 90**

On Ubuntu 20 (WSL) the error is slightly different, but points to the same:

ivo@DESKTOP-KN14QQK:~/vale$ python3 valec.py build float_operations.vale
Running: java -cp /home/ivo/vale/Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast float_operations.vale
Running: /home/ivo/vale/valec --verify --output-dir . build.vast
valec couldn't compile build.vast:
Region override: assist
Warning: not using census when in assist mode!

**valec: /home/valerian/Vale/Midas/src/c-compiler/function/expressions/externs.cpp:90: Ref translateExternCall(GlobalState *, FunctionState *, BlockState *, LLVMBuilderRef, ExternCall *): Assertion `false' failed.**

Looking at the current code in externs.cpp, it probably just means its implementation in Vivem is commented out for the time being.

![image](https://user-images.githubusercontent.com/963452/111296522-e0145f00-864c-11eb-9b46-c45fcbbcf18d.png)

**Comment by Verdagon** [comment]
Fixed as of #208! Will also verify on windows on release. Thanks for reporting this Ivo!
