### ISSUE TITLE
print doesn't work for float type

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#116]
Compiling this test code on Windows 10 and Ubuntu 20:

```
  a = 42.9;
  println(a);
```

gives this error:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast float_operations.vale

float_operations.vale:3:3: Couldn't find a suitable function named `println` with args (float):
  println(a);

Rejected candidates:
  builtins/printutils.vale:2:1: println
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Str2())
  builtins/printutils.vale:6:1: println
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Int2())
  builtins/printutils.vale:10:1: println
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Bool2())
  builtins/strings.vale:218:1: println
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))

Obviously a functionality that still has to  be added, so not to worry too much.

Strangely enough the abort error from issue #114 on Windows 10 doesn't appear with this code; it comes back when commenting the println line.

**Comment by Verdagon** [comment]
Fixed as of https://github.com/ValeLang/Vale/pull/205! Closing, will also verify on windows on release.
