### ISSUE TITLE
Other float operations which are not yet implemented

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#117]
Compiling this test code on Windows 10 and Ubuntu 20:

```

  a = 42.9;
  pi = 3.1415;
  println(a == pi);
```

gives this error:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast float_operations.vale

float_operations.vale:4:11: Couldn't find a suitable function named `==` with args (float, float):
  println(a == pi);

Rejected candidates:
  builtins/strings.vale:172:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/builtinexterns.vale:76:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Bool2())
  builtins/strings.vale:173:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/strings.vale:170:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Str2())
  builtins/strings.vale:171:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Str2())
  builtins/builtinexterns.vale:79:1: ==
    Param at index 0 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Int2())

Obviously a functionality that still has to  be added, so not to worry too much.

Strangely enough the abort error from issue #114 on Windows 10 doesn't appear with this code; it comes back when commenting the println line.

Same for:   
!=

**Adding an int and a float**:
```
  pi = 3.1415;
  a = 9;
  println(a + pi);

```
Running: java -cp /home/ivo/vale/Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast test.vale

test.vale:4:11: Couldn't find a suitable function named `+` with args (int, float):
  println(a + pi);

Rejected candidates:
  builtins/castutils.vale:14:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Str2())
  builtins/castutils.vale:6:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Str2())
  builtins/strings.vale:212:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/strings.vale:211:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/castutils.vale:10:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Str2())
  builtins/builtinexterns.vale:40:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Float2())
  builtins/builtinexterns.vale:37:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Int2())
  builtins/builtinexterns.vale:5:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Str2())
  builtins/strings.vale:210:1: +
    Param at index 0 doesn't match: Coord(Share,Int2()) cannot convert to Coord(Share,Str2())

**Concatenating a string and a float**
The code:
```
   println("The holy number is: " + 3.14);
```
Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast test.vale

test.vale:2:11: Couldn't find a suitable function named `+` with args (str, float):
  println("The holy number is: " + 3.14);

Rejected candidates:
  builtins/builtinexterns.vale:40:1: +
    Param at index 0 doesn't match: Coord(Share,Str2()) cannot convert to Coord(Share,Float2())
  builtins/castutils.vale:10:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Int2())
  builtins/builtinexterns.vale:5:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Str2())
  builtins/builtinexterns.vale:37:1: +
    Param at index 0 doesn't match: Coord(Share,Str2()) cannot convert to Coord(Share,Int2())
  builtins/strings.vale:210:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/strings.vale:212:1: +
    Param at index 0 doesn't match: Coord(Share,Str2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/castutils.vale:14:1: +
    Param at index 1 doesn't match: Coord(Share,Float2()) cannot convert to Coord(Share,Bool2())
  builtins/strings.vale:211:1: +
    Param at index 0 doesn't match: Coord(Share,Str2()) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))
  builtins/castutils.vale:6:1: +
    Param at index 0 doesn't match: Coord(Share,Str2()) cannot convert to Coord(Share,Int2())

**Comment by Verdagon** [comment]
Fixed as of #208! Except for the 3.14159 + 9 case, filed #207 for that to think it over a bit more.

Will also verify on windows on release. Thanks for reporting this Ivo!
