### ISSUE TITLE
Function splice has not the correct return type

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#118]
String function splice defined in:

https://github.com/ValeLang/Vale/blob/master/Valestrom/Samples/test/main/resources/builtins/strings.vale

has no return type, but needs return type str

For example, when used in: println("sprogwoggle".splice(4, 1, "bble"));

it gives the error:

builtins/strings.vale:204:1: Function builtins/strings.vale:204:1: 
splice return type Coord(Share,Void2()) doesn't match body's result: Coord(Share,Str2())

**Comment by Verdagon** [comment]
Fixed at head! On next release, will verify this on windows too. Thanks for finding this Ivo!
