### ISSUE TITLE
Compound boolean and expression combined with == operator in if statement

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#120]
These statements all work:

```
n = 4;
  if (n > 2 and n < 5) { println("The number is either 3 or 4"); }
  // => The number is either 3 or 4
  // same:
  if (and(n > 2, n < 5)) { println("The number is either 3 or 4"); }
  // => The number is either 3 or 4
  
  m = 1;
  if (m > 2 or m < 5) { println("Bigger than 2 or smaller than 5"); }
  // => Bigger than 2 or smaller than 5
  if (or(m > 2, m < 5)) { println("Bigger than 2 or smaller than 5"); }
  // => Bigger than 2 or smaller than 5

  if (n == 4 and m == 1)  { println("This works!"); }  // <--
 ```

However, if we rewrite the last statement (<--) as:

```
 if (and(n == 4, m == 1)) { println("Right on!"); } 
```

we get the error:
** expected `;` or `}` after expression, but found:
(and(n == 4, m == 1)) { println("Right on!"); }**

Remark: on the other hand, that last construct seems to work fine in roguelike.vale:

```
if (and(rowI == goblin.location.values.1, cellI == goblin.location.values.0)) {
            mut charToPrint = "g";
}
```
I don't see why the first version doesn't compile and the second does.

**Comment by Verdagon** [comment]
I can't seem to repro this one. It's possible it was accidentally fixed since reported. Will close it for now, but let me know if you see something like this again!

**Comment by Ivo-Balbaert** [comment]
I can confirm that this version works in v0.1.2, thanks!
