### ISSUE TITLE
Better error messages when trying to change a tuple

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#121]
Tuples are immutable in Vale.

The compiler should give a clearer message here. As of now, when trying to change elements, it gives a compiler error, but they are incomprehensible:
(following statements are from main() in a program tuples.vale)

t2 = [5, true, "V"];          

t2.1 = false;        // =>  **error: expected `;` or `}` after expression, but found: = false;**
t2.0 = 42;           // same error
t2[0] = 42;          // same error

mut t2.1 = false;
  **// Internal error while compiling [PureWindowsPath('tuples.vale')]:
  // Exception in thread "main" java.lang.RuntimeException: impl
...**

**Comment by Verdagon** [comment]
Now we show this error:
```/Users/verdagon/main.vale:3:7: Cannot mutate final member '1' of container TupleName2(List(Coord(Share,Readonly,Int2()), Coord(Share,Readonly,Bool2()), Coord(Share,Readonly,Str2())))
```

The incomprehensible type names are irksome, but that's a battle for another day...

Will mark this fixed when the release hits the site. Thanks Ivo!

**Comment by Ivo-Balbaert** [comment]
The new error message would be great. Testing in v 0.1.2 (I'm pretty sure of that) on Windows and still getting the old message:

**Comment by Verdagon** [comment]
Given the original code:
```
fn main() export {
  t2 = [5, true, "V"];
  t2.1 = false; // => error: expected ; or } after expression, but found: = false;
  t2.0 = 42; // same error
  t2[0] = 42; // same error
  mut t2.1 = false;
}
```
it now gives the error:
`Error: /Users/verdagon/main.vale:4:3 error S: : Changing a struct's member must start with the `set` keyword.`

Which is an improvement =D

When we add `set` keywords (same as `mut`, either words):
```
fn main() export {
  t2 = [5, true, "V"];
  set t2.1 = false; // => error: expected ; or } after expression, but found: = false;
  set t2.0 = 42; // same error
  set t2[0] = 42; // same error
  set t2.1 = false;
}
```
we get the error:
`Error: /Users/verdagon/main.vale:3:7 error T: : Cannot mutate final member '1' of container TupleNameT(List(CoordT(share,ro,IntT(32)), CoordT(share,ro,BoolT()), CoordT(share,ro,StrT())))`

Will test on windows too before release.
