### ISSUE TITLE
A list cannot be printed out

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#124]
The following code in lists.vale:

```
fn main() export {
  lst = List<int>();
  lst.add(1);
  lst.add(3);
  lst.add(7);
  println(lst);
}
```

compiled with: python ..\valec.py build lists.vale ..\vstl\list.vale

gives the compiler error:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast lists.vale ..\vstl\list.vale

lists.vale:12:3: **Couldn't find a suitable function named `println` with args (??List<?int>)**:
  println(lst);

Rejected candidates:
  builtins/printutils.vale:2:1: println
    Param at index 0 doesn't match: Coord(Own,StructRef2(FullName2(List(),CitizenName2(List,List(CoordTemplata(Coord(Share,Int2()))))))) cannot convert to Coord(Share,Str2())
  builtins/printutils.vale:6:1: println
    Param at index 0 doesn't match: Coord(Own,StructRef2(FullName2(List(),CitizenName2(List,List(CoordTemplata(Coord(Share,Int2()))))))) cannot convert to Coord(Share,Int2())
  builtins/printutils.vale:10:1: println
    Param at index 0 doesn't match: Coord(Own,StructRef2(FullName2(List(),CitizenName2(List,List(CoordTemplata(Coord(Share,Int2()))))))) cannot convert to Coord(Share,Bool2())
  builtins/strings.vale:218:1: println
    Param at index 0 doesn't match: Coord(Own,StructRef2(FullName2(List(),CitizenName2(List,List(CoordTemplata(Coord(Share,Int2()))))))) cannot convert to Coord(Share,StructRef2(FullName2(List(),CitizenName2(StrSlice,List()))))

It is possible to print out all items of a list with 
_lst.each( { println(_); } );_ 
or:
 _each &lst { println(_); }_

a generic print function for a list would be preferred.

**Comment by F0x1fy** [comment]
I'm unsure how Verdagon wishes to do the print function, but a standalone print function should be easy. Sorry to mention Odin again, but we could take some influence from its print functionality, which can print out any type within the language.

**Comment by Verdagon** [comment]
I'll add this to list.vale:
```
fn print<T>(list &List<T>) {
  print("List(");
  first! = true;
  each (&list) {
    if (not first) {
      print(", ");
    }
    mut first = false;
    print(_);
  }
  print(")");
}
fn println<T>(list &List<T>) {
  print(list);
  println("");
}
```
and that would solve the basic cases for now.

Someday, I would like to have built-in print functionality for every type... and it's uniquely easy in Vale, because single ownership means we can recursively print without infinite loops. Just have to figure out whether to do this in vale code, or built into the compiler...

Will mark this fixed when the release hits the site. Thanks for reporting this, Ivo!

**Comment by Ivo-Balbaert** [comment]
This println/print functionality indeed prints out a List, when it is added to vstl\list.vale

However in v 0.1.2, the new code was not yet added to the standard library list.vale

**Comment by Verdagon** [comment]
Not sure where that change went. I added it again to list.vale.

And tested with this, and it works!

```
import stdlib.collections.*;
fn main() export {
  s = List<str>();
  s!.add("hello ");
  s!.add("world!");
  println(&s);
}
```

Will also test on windows before next release. Thanks Ivo!
