### ISSUE TITLE
eachI on array with _ as a param doesn't work

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#126]
Remark: the error message might be justified, in that case this issue can be closed immediately.

The following uses of each and eachI on an array work great:

```
fn main() export {
  arr2 = MakeArray(4, {_ * 2}); // [0, 2, 4, 6]
  arr2.each( { println(_); } );
// =>
// 0
// 2
// 4
// 6
// simpler form:
  each &arr2 (n){ println(n); }
// =>
// 0
// 2
// 4
// 6
// still shorter simpler form:  
  each &arr2 { println(_); }
// =>
// 0
// 2
// 4
// 6
  eachI &arr2 (ix, p){ println("On index: " + ix + " is item: " + p); }
// =>
// On index: 0 is item: 0
// On index: 1 is item: 2
// On index: 2 is item: 4
// On index: 3 is item: 6
```
However the following form:

```
eachI &arr2 (ix, _){ println("On index: " + ix + " is item: " + _); }
```

gives the error:

c:\Vale\code_examples>python ..\valec.py build arrays.vale
Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast arrays.vale

arrays.vale:44:15**Cant have a lambda with _ and params**

**Comment by Verdagon** [comment]
This error message is WAI, but I'm curious about this use case. Do you think users will make this mistake a lot? I'd hope that they'd know what `_` is for and not accidentally use it like a regular parameter.

**Comment by Ivo-Balbaert** [comment]
You are right that this is a very improbable error. If a user would want to use the index ix explicitly, he/she also will probably explicitly use a parameter. It is best to explicitly forbid this usze case of ix and _ used together.
Perhaps the error message can be made a little more obvious:  Can't have a lambda with _ and other params or indices

**Comment by Verdagon** [comment]
This example now prints the error:
`Error: /Users/verdagon/main.vale:29:13 error S:  Cant have a lambda with _ and params`

Thanks for reporting this, Ivo! Will test on windows too before release.
