### ISSUE TITLE
Immutable locals (finals) can be changed

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#128]
(Vale v 0.1.1)

```
fn main() export {
  x = "world!";
  mut x = "changed";
  println(x); // => changed

  c = 4;
  mut c = c + 1;
  println(c); // => 5
}
```

The x and c in the snippet above are immutable, nevertheless they are changed with mut.
The code behaves the same as if it would contain  x!  and c!

**Comment by Verdagon** [comment]
Added error message:
```
/Users/verdagon/main.vale:3:7: Cannot mutate final local "x".
```
Will mark this fixed when this release hits the site. Thanks a bunch, Ivo!
