### ISSUE TITLE
Better error message when trying to change a final field of a struct

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#130]
The following code snippet:

```
// struct with final fields:
struct Spaceship {
  name str;
  numWings int;
}

fn main() export {
  ship = Spaceship("Serenity", 2); 
  println(ship.name);              // => Serenity
  ship.name = "Enterprise";        // <-- 
}
```

correctly gives a compiler error in the line indicated with <-- because the name field is final.

The error is:  **expected `;` or `}` after expression, but found: = "Enterprise";**

This message should be made more clear to indicate that there was an attempt to change a final field.

Of course, defining the field as 

                        name! str;

allows to change its contents with:

                        mut ship.name = "Enterprise"; 

Probably related to #121

**Comment by Verdagon** [comment]
Added a better error message for when someone tries to change a field without the `mut` keyword:
```
/Users/verdagon/main.vale:10:3: Changing a struct's member must start with the `mut` keyword.
```
And, when we do add the `mut` keyword, we now have a message about changing a final member:
```
/Users/verdagon/main.vale:10:7: Cannot mutate final member 'name' of struct Spaceship
```
Will mark this fixed when this release hits the site. Thanks Ivo!

**Comment by Ivo-Balbaert** [comment]
For the code snippet above, I still get the same error message:

struct_with_final_fields.vale:10:13: expected `;` or `}` after expression, but found:
= "Enterprise";        // <--

**Comment by Verdagon** [comment]
Just tried it again, and I get the same result as last time.

I'm guessing you're using a different version, or I mixed up the release last time or something.

Will also test on windows before next release. Thanks Ivo!
