### ISSUE TITLE
An immutable struct should not contain non-final fields

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#131]
The following code snippet compiles and executes without any error:

```
struct Spaceship imm {
  name! str;
  numWings int;
}

fn main() export {
  ship = Spaceship("Serenity", 2); 
  println(ship.name);              // => Serenity
}
```

I think this should be a compiler error.

When the following statement is added as the last statement:                  mut ship.name = "Enterprise"; 

we do get a compiler error:

(on Windows): an Abort/Retry/Ignore Debug Error! screen from Microsoft Visual C++ Runtime Library on program valec.EXE

and on the terminal:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast struct1.vale
Running: C:\Vale\valec.EXE --verify --output-dir . build.vast
valec couldn't compile build.vast:
Region override: assist
Warning: not using census when in assist mode!

Assertion failed: refM->ownership == ownership, file C:\Users\Valerian\Vale\Midas\src\c-compiler\function/expressions/shared/ref.h, line 59

A more comprehensible error message should be appropriate here.

**Comment by Verdagon** [comment]
Added a message about not being able to mutate a final member:

```
/Users/verdagon/main.vale:8:7: Cannot mutate final member 'name' of struct Spaceship
```

and also an error when we have a varying member in an imm struct:

```
/Users/verdagon/main.vale:2:3: Immutable struct ("Spaceship") cannot have varying member ("name").
```

Will mark closed when the next release hits the site. Thanks Ivo!

**Comment by Ivo-Balbaert** [comment]
This is a great improvement in error messages!

When should the error message: "Immutable struct ("Spaceship") cannot have varying member ("name")." appear?

In the original code? This still compiles for me as before:

struct Spaceship imm {
  name! str;
  numWings int;
}

fn main() export {
  ship = Spaceship("Serenity", 2); 
  println(ship.name);              // => Serenity
}

Could you give an example where the 2nd error message appears please?

**Comment by Verdagon** [comment]
Compiled this code:
```
struct Spaceship imm {
  name! str;
  numWings int;
}
fn main() export {
  ship = Spaceship("Serenity", 2); 
  println(ship.name);              // => Serenity
}
```

and it gives the error: `Error: /Users/verdagon/main.vale:2:3 error T: : Immutable struct ("Spaceship") cannot have varying member ("name").`

I'm guessing you're using a different version, or I mixed up the release last time or something.

Will also test on windows before next release. Thanks Ivo!
