### ISSUE TITLE
Fix working on vale.dev

### ISSUE THREAD

**Issue by F0x1fy** [ValeLang/Vale#136]
On introduction#arrays:
> We can only make a tuple if we know the number of elements at compile-time. If we don't know, then we must use an **array**.

Needs to be changed to

> We can only make a tuple if we know the number of elements at compile-time. If we don't know, then we must use a runtime-sized **array**.

**Comment by Verdagon** [comment]
Fixed in https://github.com/ValeLang/Site/pull/22, thanks for filing this!
