### ISSUE TITLE
Using module names for consistent ABI

### ISSUE THREAD

**Issue by F0x1fy** [ValeLang/Vale#165]
It would be incredibly useful to use module names/namespaces for a consistent ABI. This will help collisions.

Example:
```
foo.baz // -> `baz` -> Collision
bar.baz // -> `baz` -> Collision
```
```
foo.baz // -> `foo_baz` -> No collision
bar.baz // -> `bar_baz` -> No collision
```
This would be best with enforced modules/namespaces, meaning that there's no way for a function to collide with another *outside of* ***explicit*** symbol name export, if that is given as an option. There still is the possibility of collision, but it would require two exact module names and two exact function names, which is unlikely and easy to work around if it occurs.

**Comment by Verdagon** [comment]
Done in #231!
