### ISSUE TITLE
Postfix ! on list variable when list is changed - 2 versions of std list.vale

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#178]
In V 0.1.2 it is now necessary to add a ! to a list variable when the list is changed, for example in:
lst!.add  lst!.set   lst!.remove

But this is not yet done in the list library itself, neither in vstl/list.vale , nor in samples/libraries/list.vale
In both files, these are the lines to be changed:

                list!.add(elem);
		result!.add(haystack);
		result!.add(first);

Moreover, both list.vale files are different. They differ in the add function, and the samples/libraries version has an additional get method, and a join and map method which the first does not have.
If it is at all necessary to keep two versions of list.vale, please synchronize.

**Comment by Ivo-Balbaert** [comment]
Also the code from roguelike.vale in samples should be adapted likewise, following lines have to change adding postfix !:

goblins!.add(13, Goblin(Vec([6, 3]))); // [col, row]
  goblins!.add(14, Goblin(Vec([2, 6])));
  goblins!.add(15, Goblin(Vec([5, 7])));
  goblins!.add(17, Goblin(Vec([2, 5])));
  goblins!.add(19, Goblin(Vec([7, 1])));
  goblins!.add(23, Goblin(Vec([3, 3])));
  goblins!.add(24, Goblin(Vec([1, 7])));
  goblins!.add(25, Goblin(Vec([7, 6])));
  goblins!.add(27, Goblin(Vec([4, 6])));
  goblins!.add(29, Goblin(Vec([7, 4])));

 goblins!.remove(key);

**Comment by Verdagon** [comment]
Done in 0.2! Thanks for reporting this.
