### ISSUE TITLE
Export things in a directory structure corresponding to their module (and maybe package)

### ISSUE THREAD

**Issue by Verdagon** [ValeLang/Vale#212]

**Comment by divinusdracodominus** [comment]
correction: generate headers file extern/export regardless of import (this doesn't exclude export by package, export by package just becomes redundant)

**Comment by Verdagon** [comment]
This issue is actually referring to how we dump every generated .h into the `--output-dir` directory. Would probably be a bit nicer to output it into subdirectories according to the module name (and maybe package names?)

After all, multiple modules might be exporting things of the same name, which would cause collisions.

**Comment by Verdagon** [comment]
Done in #232!
