### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by Verdagon** [ValeLang/Vale#228]

**Comment by F0x1fy** [comment]
I feel your title and description were too generic, could you elaborate further? lol

**Comment by Verdagon** [comment]
I really need to keep in mind that others read these issues hahah

Basically, I want to:
- add concepts to our current template-based system (this is mostly there today, funny story)
- do type-checking on these functions ahead of time, except for lambdas
- be able to opt-out of the ahead-of-time type-checking, perhaps with a "template" keyword

Later on, probably not as part of this, we would want to have a mode to monomorphize or not.

**Comment by Verdagon** [comment]
Done as of https://github.com/ValeLang/Vale/commit/93eb8e140bbbda3a8f47099b3215c5eb700c90f6!
