### ISSUE TITLE
Better each/eachI syntax

### ISSUE THREAD

**Issue by Verdagon** [ValeLang/Vale#243]
How about:

```
each x in myList {
  ...
}
```

```
each key, x in myMap {
  ...
}
```

**Comment by Verdagon** [comment]
We should also do something where a statement-level `{` makes the entire line into a foreach loop.
```
something x, y, z in blah {
   ...
}
```
should be conceptually lowered to:
```
foreach blah.something() (x, y, z){
   ...
}
```
(`.something()` returns an iterator, and foreach will advance the iterator calling the given lambda)

**Comment by Verdagon** [comment]
Whatever we do, make sure we dont need a & on the container, today we sometimes need one.

**Comment by elimisteve** [comment]
> How about:
> 
> ```
> each x in myList {
>   ...
> }
> ```
> 
> ```
> each key, x in myMap {
>   ...
> }
> ```

These sound very good to me, but is there any reason not to do

```
for x in myList {
  ...
}
```

and

```
for i, x in myList {
  ...
}
```

?

**Comment by Verdagon** [comment]
This is done actually, foreach loops are now `foreach x in myList { ... }` and `foreach [k, v] in myList { ... }`
