### ISSUE TITLE
Array Programming

### ISSUE THREAD

**Issue by sirinath** [ValeLang/Vale#26]
Can we have array programming constructs like ranges, slices, broadcasting, elementwise operators and array level operators, etc.

**Comment by Verdagon** [comment]
We have plans for some of the things you mention:

- The *. operator ("map" operator) will run an arbitrary function on all elements of an array: myArrayOfSpaceships*.liftoff(5) will call the `liftoff(spaceship, height)` function on all elements (this is called the map operator).
- The |. operator ("flatMap" operator) will do the same, and then flatten the result.

Ranges and slices can be implemented in Vale code, so they might make it into the standard library.

I'm not familiar with broadcasting, what is that? And what do you mean by array level operators?

**Comment by sirinath** [comment]
- https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm
- https://xtensor.readthedocs.io/en/latest/expression.html#broadcasting

Also see:
- http://www.sac-home.org/

**Comment by Verdagon** [comment]
Thanks for suggesting this! That's an interesting feature that Julia added.

I'm not convinced that this is worth adding syntactical support for, in Vale. It seems like a very niche use, not something worth complicating the language for, especially when (it looks like) it can be done with a custom function.
