### ISSUE TITLE
Include stdlib by default

### ISSUE THREAD

**Issue by Verdagon** [ValeLang/Vale#341]

**Comment by Verdagon** [comment]
Perhaps have suggestions for when we see a /src folder in a dependency

**Comment by F0x1fy** [comment]
Trying to include stdlib on 0.13 using (my location for Vale) `stdlib=~/Programming/Compilers/Vale/stdlib/src` (with `:` and `=`) does not load stdlib, specifically printing for ints

**Comment by Verdagon** [comment]
And dont require a `import stdlib.*;` at the top

**Comment by Verdagon** [comment]
Done in 0.2! (except for `import stdlib.*;`, we'll keep that for now)
