### ISSUE TITLE
Claims regarding Rust not being memory safe.

### ISSUE THREAD

**Issue by gimbles** [ValeLang/Vale#483]
![image](https://user-images.githubusercontent.com/93856041/164955565-2f19607f-7d77-46fd-930b-b89a1fcd0fef.png)
![image](https://user-images.githubusercontent.com/93856041/164955586-8f22faaf-57f7-4ed7-b002-df6d625d5898.png)
![image](https://user-images.githubusercontent.com/93856041/164955641-dc9cc2be-b29b-4da3-b570-52c59d77dec0.png)
![image](https://user-images.githubusercontent.com/93856041/164955667-608022b6-0d53-48d5-b1ff-67a727f6a4c1.png)

Citation oh-so-badly needed.

**Comment by gimbles** [comment]
The borrow checker does _not_ push you into using centralized Vecs and HashMaps.

Neither does it absolutely add any runtime overhead.

**Comment by gimbles** [comment]
> it can cause memory unsafety outside, in safe Rust as well

You should elaborate on 

- What memory unsafety issues
- How to perform them

before claiming that safe Rust can have memory unsafety.

**Comment by nekodjin** [comment]
So true meowstie.

**Comment by Verdagon** [comment]
Thanks for filing! Always glad to have people double-checking the site.

To your points:

1. Java allows us to keep multiple references to a mutable object. In Rust, we must put them into a central place (usually a Vec or HashMap), and replace all references but one with an index or an ID. We then incur costs to go from an index/ID to a borrow reference, namely bounds checks or hashing.

2. It's pretty trivial to do some casting in an unsafe block, and hand that back to safe code, to later cause a segfault. I've heard it referred to by other Rust users as "leaky safety", but it might not be a widespread term.

These are pretty well-known to experienced Rust devs, but I can add some examples and citations if enough folks don't recognize the pattern.

Closing this for now, but thanks for asking!
