### ISSUE TITLE
Broken link in Perfect replayability post

### ISSUE THREAD

**Issue by CeleritasCelery** [ValeLang/Vale#516]
[footnote 6](https://verdagon.dev/blog/perfect-replayability-prototyped#note6) in the Perfect Replayability post goes to this URL https://github.com/Verdagon/Vale/blob/master/docs/DeterministicReplayability.md which does not exist.

**Comment by ngoduyanh** [comment]
Looking at the git history, that should be [https://github.com/ValeLang/Vale/blob/master/docs/PerfectReplayability.md](https://github.com/ValeLang/Vale/blob/master/docs/PerfectReplayability.md)

**Comment by Verdagon** [comment]
Fixed, thank you for reporting this!
