### ISSUE TITLE
Support for Builders

### ISSUE THREAD

**Issue by sirinath** [ValeLang/Vale#58]
Is it possible to support builders in Vale. This has been implemented in:
- https://kotlinlang.org/docs/reference/type-safe-builders.html
- http://groovy-lang.org/dsls.html#_builders
- https://dotty.epfl.ch/docs/reference/contextual/context-functions.html

**Comment by Verdagon** [comment]
Interesting idea! We'll not be adding this, because this makes if-statements more difficult.

For example:
```
if someCondition() {

}
```
it's hard to tell whether that opening brace is opening a builder call, or the body of the if-statement.
