### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by nmsobri** [ValeLang/Vale#586]
Hi there.. I want to know the status of this project.. Is it still being developed or completely abandon. Judging from the commit history, there is no new commit for the last 3 months..

**Comment by Verdagon** [comment]
Howdy! This project is still very alive and active, though that activity doesn't really show up here.

Lately I'm developing on the "saferegioncomplete" branch of my personal fork at https://github.com/verdagon/vale/tree/saferegioncomplete, and I post an update every day or two to the #progress channel of the discord server.

(Leaving this open until I can figure out a good way to show progress even when there's nothing I can merge into master)

**Comment by BenjaBobs** [comment]
If it's just about showing progress, you could always start a pull request as soon as you branch out.
That way, every time you push, the pull request will be updated and people who subscribed to the pull request (or the repo) will get notifications, and the "last updated" date on the pull request will be updated.

It can lead to clutter, but it increases visibility.

**Comment by nmsobri** [comment]
> Howdy! This project is still very alive and active, though that activity doesn't really show up here.
> 
> Lately I'm developing on the "saferegioncomplete" branch of my personal fork at https://github.com/verdagon/vale/tree/saferegioncomplete, and I post an update every day or two to the #progress channel of the discord server.
> 
> (Leaving this open until I can figure out a good way to show progress even when there's nothing I can merge into master)

ah ic.. sorry didn't aware of the discord channel.. hope you keep this project going on cause I see a lot of potential in this language
