### ISSUE TITLE
LLVM12

### ISSUE THREAD

**Issue by chadbrewbaker** [ValeLang/Vale#78]
Is there any reason it is pinned to LLVM7?

**Comment by chadbrewbaker** [comment]
LLVM@7 brew package hardcodes LIBOMP_ARCH=x86_64 - let the yak shaving for aarch64 begin.

**Comment by Verdagon** [comment]
To save a few months, we forked our codegen phase (Midas) from the Cone compiler, which was using LLVM7, so we inherited that decision. Upgrading it to LLVM 10 or 11 could improve things, and might even be easy, but we're tied up with error infrastructure and documentation. Anyone is welcome to try this =)

**Comment by chadbrewbaker** [comment]
https://github.com/Homebrew/homebrew-core/pull/65329 I fixed the arm64 build issue but valgrind is still barfing.

I'll bump Midas and see how it compiles with mainline llvm.

**Comment by Verdagon** [comment]
Now works with LLVM 11! Closing this out.
