### ISSUE TITLE
Unable to compile roguelike.vale

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#81]
Hi, great project!

Following the installation instructions, I had to use python3.9 instead of 3.7
When running tests, I found:
test$ python3.9 -m unittest -f

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Is this ok?

When running the command:
$ python3.9 valec.py test/tests/roguelike.vale

I stumbled upon the error:

No VALEC_PATH in env, assuming the one in cmake-build-debug.
Running: java -cp  net.verdagon.vale.driver.Driver build -o ./build.vir test/tests/roguelike.vale /home/ivo/Vale/Midas/vstl/arrayutils.vale /home/ivo/Vale/Midas/vstl/utils.vale /home/ivo/Vale/Midas/vstl/castutils.vale /home/ivo/Vale/Midas/vstl/printutils.vale /home/ivo/Vale/Midas/vstl/strings.vale /home/ivo/Vale/Midas/vstl/opt.vale
Internal error while compiling ['test/tests/roguelike.vale', '/home/ivo/Vale/Midas/vstl/arrayutils.vale', '/home/ivo/Vale/Midas/vstl/utils.vale', '/home/ivo/Vale/Midas/vstl/castutils.vale', '/home/ivo/Vale/Midas/vstl/printutils.vale', '/home/ivo/Vale/Midas/vstl/strings.vale', '/home/ivo/Vale/Midas/vstl/opt.vale']:

Error: Could not find or load main class net.verdagon.vale.driver.Driver
Caused by: java.lang.ClassNotFoundException: net.verdagon.vale.driver.Driver

Any idea what went wrong? My local Vale repo is up to date with GitHub.
Thanks!

**Comment by Ivo-Balbaert** [comment]
The problem seems to be only that files are not at the location where the commands expect them to be.

My Ubuntu verson: Ubuntu 20.04.1 LTS
My Java version is: 
java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

Using Python 3.9

I work in the Midas folder. By copying Valestrom.jar in that folder I was able to compile a hello world Vale program:

~/Vale/Midas$ python3.9 valec.py hello.vale
No VALEC_PATH in env, assuming the one in cmake-build-debug.
Running: java -cp /home/ivo/Vale/Midas/Valestrom.jar net.verdagon.vale.driver.Driver build -o ./build.vir hello.vale /home/ivo/Vale/Midas/vstl/arrayutils.vale /home/ivo/Vale/Midas/vstl/utils.vale /home/ivo/Vale/Midas/vstl/castutils.vale /home/ivo/Vale/Midas/vstl/printutils.vale /home/ivo/Vale/Midas/vstl/strings.vale /home/ivo/Vale/Midas/vstl/opt.vale
Running: /home/ivo/Vale/Midas/cmake-build-debug/valec --verify --output-dir . ./build.vir
Running: clang-7 -O3 -lm -o ./a.out ./build.o /home/ivo/Vale/Midas/src/valestd/math.c /home/ivo/Vale/Midas/src/valestd/census.c /home/ivo/Vale/Midas/src/valestd/assert.c /home/ivo/Vale/Midas/src/valestd/weaks.c /home/ivo/Vale/Midas/src/valestd/stdio.c /home/ivo/Vale/Midas/src/valestd/genHeap.c /home/ivo/Vale/Midas/vstl/strings.c
Compiled to ./a.out
~/Vale/Midas$ ./a.out
Hello world!

I found the roguelike.vale program in the folder ~//Vale/Valestrom/Samples/test/main/resources/programs. After copying it to the Midas folder, I could compile it. When executing, it shows the map, but seems to not respond to keyboard input:

ivo@ivo-SATELLITE-L50D-B:~/Vale/Midas$ ./a.out
##########
#........#
#........#
#........#
#..@..#
#........#
#........#
#........#
#........#
##########

Also, the command python3.9 valec.py test/tests/roguelike.vale doesn't find any tests. Perhaps they are also at ~//Vale/Valestrom/Samples/test/main/resources/programs ?

Thanks.

**Comment by Verdagon** [comment]
Thanks for this report! I made the roguelike.vale program print out its controls, and explicitly tell the user they need to hit enter to move the character. I also added a line to the README.txt which says that we can run the roguelike with `python3 valec.py build samples/programs/roguelike.vale vstl/hashmap.vale vstl/list.vale`.

I'm not really sure of a good short-term patch for the python version problem. Hopefully soon, we'll be able to completely replace our python scripts with Vale programs, which won't have these same problems. I'll leave this open until then.

**Comment by Ivo-Balbaert** [comment]
I can confirm that the game works on Windows 10 and Ubuntu 28 with version 0.1.1
I think roguelike.vale is important as a (at this time) 'flagship' example of Vale. 
Perhaps it should be shown more in the picture on the Vale website.
Thanks, closing this issue and opening a new for the Python suggestion, which is more of a feature request.
