### ISSUE TITLE
 Help flag from compile-script valec.py gives no help.

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#88]
This should work according to the Download page, which states: _Use python3 valec.py help for help._ 
Instead ist gives the following output:

c:\Vale\code_examples>python ..\valec.py help Valestrom path: C:\Vale Builtins path: C:\Vale\builtins No VALEC_PATH in env, assuming the one in current directory. valec path: C:\Vale\Midas.exe Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC. _Unrecognized input: help_ 

So this feature is probably missing from the options parsing, or does not get redirected correctly on to Valestrom/Midas.

If you give me the text which should appear after help, I can make a PR request to solve this.

**Comment by Verdagon** [comment]
Fixed valec.py to be able to print some help, will close this on next release. Thanks for catching this!

**Comment by Verdagon** [comment]
Fixed in v0.1.1. Thanks Ivo!
