### ISSUE TITLE
Couldn't find a suitable function named `split`

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#90]
On the first page of the Guide: (https://vale.dev/guide/introduction) $ Functions,
the code snippet:

fn main() export {
  s = "Hail Hydra!".split(" ");
  s = split("Hail Hydra!", " ");
}

gives the compiler error:

ufcs.vale:2:8: Couldn't find a suitable function named `split` with args (str, str):

**Comment by Verdagon** [comment]
If we had our import system figured out, this would be a great place to do `import List;`...

...for now, I'm adding a note "For the `split` function, include vstl/list.vale on the command line."

Will mark this fixed in the next push. Thanks for the report!

**Comment by Verdagon** [comment]
Fixed in v0.1.1. Thanks Ivo!
