### ISSUE TITLE
Compile Error for arr[1 + 1]

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#91]
On the first page of the Guide: (https://vale.dev/guide/introduction) $ Arrays
the code snippet:

fn main() export {
  arr = [5, true, "V"];
  println("Babylon " + arr.0);          // => Babylon 5
  println("Saturn " + arr[2]);          // => Saturn V
  println("Saturn " + arr[1 + 1]);      <---
}

gives the following compiler error in the line with <--:

// Exception in thread "main" java.lang.RuntimeException: impl random access of structs' members

**Comment by Verdagon** [comment]
This one was correctly marked as "coming soon" on the site. I suspect now that i'm not making that visible/clear enough to the readers, it's very easy to miss. I think the right call here would be to also shade the background color from white to something else when i'm talking about future features. Will think on this more.

**Comment by Ivo-Balbaert** [comment]
The marking "coming soon" is already clear enough.
Perhaps what I really want to say is: just add the line:
                                             println("Saturn " + arr[2]); // => Saturn V
before the arr[1+1], so that people see the normal way of indexing which already works.
I will propose this change in a forthcoming PR for the site.

**Comment by Verdagon** [comment]
I removed the arr[1 + 1], since I'm not sure that works yet. `arr.2` does work though.

I also moved all future features into afterwords in the guide, so it's clearer what's coming soon. Well, except for the regions page, which is _all_ future features.

I'll mark this fixed when the site's deployed next. Thanks for finding these!

**Comment by Verdagon** [comment]
Fixed and deployed, thanks Ivo!
