### ISSUE TITLE
Couldn't find a suitable function named `inputInt`

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#92]
On the first page of the Guide: (https://vale.dev/guide/introduction) $ Arrays,
the code snippet:

fn main() export {
  n = inputInt(); 9
  arr = Array(n, {_ * 5}); 10
  println(arr);
}
gives the compiler error:

Couldn't find a suitable function named `inputInt` with args ():
//  n = inputInt(); 
// No function with that name exists.
// Perhaps you forget to include a file in the command line?

**Comment by Verdagon** [comment]
Changed this to stdinReadInt, and added a note saying it's an experimental function and the stdin API will change.

Thanks for finding this! Will close in the next release.

**Comment by Verdagon** [comment]
Fixed in v0.1.1. Thanks Ivo!
