### ISSUE TITLE
Couldn't find a suitable function named `eachI`

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#95]
On the first page of the Guide: (https://vale.dev/guide/introduction) $ Loops,
the code snippet:

fn main() export {
  arr = ["Storm", "Earth", "Fire"];
  eachI arr (i, x){
    println(i + ": " + x);
  }
}
gives the compiler error:

Couldn't find a suitable function named eachI with args (?3str, ??main<>().?0:319):
  }

Rejected candidates:
  C:\Vale\builtins\arrayutils.vale:64:1: eachI:
(run with --verbose to see some incomprehensible details)

**Comment by Verdagon** [comment]
Found it! There was an eachI for the Array class but not for known-size arrays.

Fixed in the nightly server (run against curl -X POST https://us-central1-valesite.cloudfunctions.net/vale-build -d @-), will mark this fixed when it has an integration test and gets into the next release.

**Comment by Ivo-Balbaert** [comment]
Thanks!

**Comment by Verdagon** [comment]
Fixed in v0.1.1. Thanks Ivo!
