### ISSUE TITLE
Compile error in weak references demo program

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#98]
Trying to compile the code snippet in § Weak References on page https://vale.dev/guide/references#weak-references of the Guide:

```
struct Base {
  name str;
}

struct Spaceship {
  name str;
  origin &&Base;
}

fn printShipBase(ship &Spaceship) {
  if ((o) = lock(ship.origin)) {                **// <-- Compile error**
    println("Ship base: " + o.name);
  } else {
    println("Ship base unknown!");
  }
}

fn main() export {
  base = Base("Zion");
  ship = Spaceship("Neb", &&base);

  printShipBase(ship);  

  base^.drop();         // Destroys base.
  printShipBase(ship);  
}
```
doesn't give the output displayed on the grey stdout pane

Ship base: Zion
Ship base unknown!

but instead gives a compile error at the line indicated with <--,  where the lock occurs:
The message is: Can't borrow a weak local, must lock()

Vale version 0.1,  the error occurs on Windows 10, as well as on Ubuntu 20.
I didn't see an indication that this feature is still in the works, so I report it here.

**Comment by Ivo-Balbaert** [comment]
The code fragment now given on Guide page https://vale.dev/guide/references, section Weak References now (v 0.1.1) compiles, which is good. In principle this issue can be closed.

However, the proposed shortcut in the sidebar 
                  15 These three lines can be reduced to **if ((o) = lock(ship.origin))** {.
still gives a compiler error:  **Couldn't figure out runes for pattern!**

I'm OK with closing this issue when 15 and 16 get a (WIP) or (soon) indication.

**Comment by Verdagon** [comment]
Added a "In future versions, " before both of them. Will mark this as closed when I deploy the site next. Thanks Ivo!
